apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "<controlPlaneEndpointAddress>:6443"
clusterName: "<clusterName>"
apiServer:
  certSANs:
  - "example-cluster"
  - "example.com"
  - "*.example.com"
networking:
  serviceSubnet: "10.111.0.0/16"
  podSubnet: "10.110.0.0/16"
