apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: idc-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.98.254.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - idc-pool
