apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "apiserver.kube.dotguin.com:6443"
clusterName: "Dotguin kubernetes service"
apiServer:
  certSANs:
  - "dotguin-cluster"
  - "dotguin.com"
  - "*.dotguin.com"
  - "*.kube.dotguin.com"
  extraArgs:
    - name: audit-policy-file
      value: "/etc/kubernetes/audit-policy.yaml"
    - name: audit-log-path
      value: "/var/log/kubernetes/audit.log"
    - name: audit-log-maxage
      value: "30"
    - name: audit-log-maxbackup
      value: "10"
    - name: audit-log-maxsize
      value: "100"
  extraVolumes:
    - name: "audit-policy-volume"
      hostPath: "/etc/kubernetes/audit-policy.yaml"
      mountPath: "/etc/kubernetes/audit-policy.yaml"
      readOnly: false
      pathType: File
networking:
  serviceSubnet: "172.19.0.0/16"
  podSubnet: "172.18.0.0/16"
